[package]
name = "unix_kit"
version = "0.1.0"
edition = "2024"

[dependencies]
fioxa_rpc.workspace = true
kernel_sys.workspace = true
kernel_userspace.workspace = true
userspace_slaballoc.workspace = true
userspace = { workspace = true, features = ["console"] }
spin.workspace = true

[lib]
crate-type = ["staticlib"]
