[package]
name = "unix_kit"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
fioxa_rpc.workspace = true
itertools = { version = "0.14.0", default-features = false, features = ["use_alloc"] }
kernel_sys.workspace = true
kernel_userspace.workspace = true
nopng = "0.1.1"
userspace_slaballoc.workspace = true
userspace = { workspace = true, features = ["console"] }
spin.workspace = true

[lib]
crate-type = ["staticlib"]
